// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// single_point_vector_rcpp
DataFrame single_point_vector_rcpp(const double& X, const double& Y, const NumericMatrix& spatial_expr);
RcppExport SEXP _spWAVE_single_point_vector_rcpp(SEXP XSEXP, SEXP YSEXP, SEXP spatial_exprSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const double& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type spatial_expr(spatial_exprSEXP);
    rcpp_result_gen = Rcpp::wrap(single_point_vector_rcpp(X, Y, spatial_expr));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_spWAVE_single_point_vector_rcpp", (DL_FUNC) &_spWAVE_single_point_vector_rcpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_spWAVE(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
