# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

single_point_vector_rcpp <- function(X, Y, spatial_expr) {
    .Call(`_spWAVE_single_point_vector_rcpp`, X, Y, spatial_expr)
}

