# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate single point vector through rcpp
#'
#' Calculate single molecular vector field from spatial coordinate and expression in one point through rcpp.
#'
#' @param X        Center point coordinates X.  
#' @param Y        Center point coordinates Y.  
#' @param spatial_expr     Spatial expression matrix, require x,y,gene expression.
#' @return         Dataframe contain Ex, Ey, U.
#' @seealso \code{\link{single_point_vector}}
#' @export 
single_point_vector_rcpp <- function(X, Y, spatial_expr) {
    .Call(`_spWAVE_single_point_vector_rcpp`, X, Y, spatial_expr)
}

